const POSH=[{id:"door",title:"Doorway first impression",need:"Photo",vs:"Normal hotel: walk in and start. Posh NG: stand at the door, then shoot."},{id:"bed",title:"Bed architecture",need:"Photo",vs:"Normal: bed looks made. Posh NG: hospital corners, pillow stack, runner centred."},{id:"vanity",title:"Vanity & chrome",need:"Photo",vs:"Normal: sink wiped. Posh NG: no water spots. Logos face forward."},{id:"wet",title:"Shower, glass & WC",need:"Photo",vs:"Normal: bathroom looks clean. Posh NG: zero hair, streak-free glass."},{id:"towels",title:"Towel sculpture",need:"Photo",vs:"Normal: towels on the rail. Posh NG: brand fold, equal reveal."},{id:"wardrobe",title:"Wardrobe, robes & safe",need:"Photo",vs:"Normal: hangers present. Posh NG: even spacing, safe reset."},{id:"desk",title:"Desk & stationery",need:"Photo",vs:"Normal: desk dusted. Posh NG: pad squared, pen parallel."},{id:"bar",title:"Minibar & glassware",need:"Photo",vs:"Normal: fridge restocked. Posh NG: labels forward, glasses polished."},{id:"touch",title:"High-touch sanitise",need:"Photo",vs:"Normal: remote on the table. Posh NG: handles, switches, handset staged."},{id:"floor",title:"Edges & under-bed",need:"Photo",vs:"Normal: vacuum the open floor. Posh NG: skirting and under-bed."},{id:"drape",title:"Window & blackout",need:"Photo",vs:"Normal: curtains drawn. Posh NG: plumb-line hang."},{id:"tech",title:"Climate + walkthrough",need:"Photo + video",vs:"Normal: AC on. Posh NG: 22C and a 15-20s walkthrough video."}];
const STANDARD=["Bed remade with fresh linen","Bathroom cleaned, toiletries replaced","Trash out, floors done","Supervisor spot-checks some rooms"];
const USERS=[{id:"sophia",name:"Sophia Adeyemi",role:"manager",title:"Duty Manager",site:"Ikeja & VI",pin:"2401",initials:"SA"},{id:"blessing",name:"Blessing Okoro",role:"housekeeper",title:"Senior Housekeeper",site:"Ikeja",pin:"4412",initials:"BO"},{id:"tunde",name:"Tunde Balogun",role:"housekeeper",title:"Room Attendant",site:"Victoria Island",pin:"5508",initials:"TB"}];
const SEED=[{id:"i201",number:"201",site:"Ikeja",type:"Deluxe King",hk:"blessing",status:"pending"},{id:"i204",number:"204",site:"Ikeja",type:"Deluxe Twin",hk:"blessing",status:"pending"},{id:"i208",number:"208",site:"Ikeja",type:"Junior Suite",hk:"blessing",status:"pending"},{id:"i212",number:"212",site:"Ikeja",type:"Deluxe King",hk:"blessing",status:"pending"},{id:"v501",number:"501",site:"Victoria Island",type:"Executive King",hk:"tunde",status:"pending"},{id:"v505",number:"505",site:"Victoria Island",type:"Executive Twin",hk:"tunde",status:"pending"},{id:"v510",number:"510",site:"Victoria Island",type:"Junior Suite",hk:"tunde",status:"submitted"},{id:"v518",number:"518",site:"Victoria Island",type:"Posh Suite",hk:"tunde",status:"pending"}];
const KEY="posh-ng-hosted-v2";
const state={user:null,view:"login",tab:"rooms",roomId:null,rooms:[],filter:"queue"};
function today(){return new Date().toLocaleDateString("en-NG",{weekday:"long",day:"numeric",month:"long"});}
function emptyEv(){const o={};POSH.forEach(p=>o[p.id]={files:[],done:false});return o;}
function load(){const raw=localStorage.getItem(KEY);if(raw){try{state.rooms=JSON.parse(raw);return;}catch(e){}}reset(false);}
function persist(){localStorage.setItem(KEY,JSON.stringify(state.rooms));}
function reset(n){state.rooms=SEED.map(r=>({...r,notes:"",managerNotes:"",evidence:emptyEv()}));const s=state.rooms.find(r=>r.id==="v510");POSH.forEach(p=>{s.evidence[p.id].done=true;s.evidence[p.id].files=[{name:p.id+".jpg",kind:"photo",demo:true}];});persist();if(n)toast("Demo rooms restored.");}
function toast(m){const el=document.getElementById("toast");el.textContent=m;el.style.display="block";clearTimeout(toast._t);toast._t=setTimeout(()=>el.style.display="none",2400);}
function room(id){return state.rooms.find(r=>r.id===id);}
function stats(hk){const list=hk?state.rooms.filter(r=>r.hk===hk):state.rooms;const c={pending:0,submitted:0,certified:0,returned:0,total:list.length};list.forEach(r=>c[r.status]++);c.cleared=c.total>0&&c.certified===c.total;return c;}
function ready(r){return POSH.every(p=>r.evidence[p.id].files.length);}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">","\"":""","'":"&#39;"}[c]));}
function label(s){return {pending:"In service",submitted:"With manager",certified:"Certified",returned:"Returned"}[s];}
function ph(){return "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=400&q=60";}
function login(u){state.user=u;state.view="app";state.tab="rooms";state.roomId=null;render();}
function logout(){state.user=null;state.view="login";render();}
function openRoom(id){state.roomId=id;state.tab=state.user.role==="manager"?"review":"room";render();}
function viewLogin(){return `<section class="login"><div class="brand"><span class="pmark">P</span> Posh Hotels & Suites \u00b7 NG</div><div class="bebar">Hosted app \u00b7 Posh Hotels & Suites Nigeria</div><h1>Every room certified before the guest arrives.</h1><p class="lede">Housekeepers send photos and a walkthrough. Duty manager certifies against the Posh Nigeria standard.</p><div class="props"><span>Ikeja</span><span>Victoria Island</span></div><div class="sheet"><p class="kicker">Staff login \u00b7 tap your name</p>${USERS.map(u=>`<button class="acct" onclick='login(${JSON.stringify(u)})'><span><strong>${u.name}</strong><small>${u.title} \u00b7 ${u.site}</small></span><span class="pin">PIN ${u.pin}</span></button>`).join("")}<button class="btn line wide" style="margin-top:8px" onclick="reset(true);render()">Reset demo rooms</button></div></section>`;}
function shell(inner){const u=state.user,mgr=u.role==="manager";return `<header class="top"><div class="brand"><span class="pmark">P</span> Certify NG</div><div style="display:flex;align-items:center;gap:8px"><div class="av">${u.initials}</div><div>${u.name.split(" ")[0]}<div class="kicker" style="color:var(--gold)">${u.site}</div></div></div></header><div class="wrap">${inner}</div><nav class="dock"><button class="${state.tab==="rooms"?"on":""}" onclick="state.tab='rooms';state.roomId=null;render()"><b>\u25a3</b>Rooms</button><button class="${state.tab==="queue"||state.tab==="review"?"on":""}" onclick="state.tab='${mgr?"queue":"rooms"}';render()"><b>\u25c9</b>${mgr?"Queue":"My job"}</button><button class="${state.tab==="standards"?"on":""}" onclick="state.tab='standards';render()"><b>\u2630</b>Standard</button><button class="${state.tab==="me"?"on":""}" onclick="state.tab='me';render()"><b>\u25cb</b>Me</button></nav>`;}
function viewRooms(){const u=state.user;const list=u.role==="manager"?state.rooms:state.rooms.filter(r=>r.hk===u.id);const s=stats(u.role==="manager"?null:u.id);return shell(`<p class="kicker">${today()} \u00b7 Posh Hotels & Suites Nigeria</p><div class="page-h"><h1>${u.role==="manager"?"House board":"My rooms"}</h1><span class="pill">${s.certified}/${s.total} certified</span></div><div class="banner"><h3>${s.cleared?"Daily job cleared":s.certified+" of "+s.total+" certified"}</h3><p>${s.cleared?"Duty manager has signed every room.":"A room is sellable only after Posh certification."}</p></div>${list.map(r=>`<article class="room"><div class="rno">${r.number}</div><div><div>${r.type}</div><div class="meta">${r.site} \u00b7 ${label(r.status)}</div></div><button class="btn gold" onclick="openRoom('${r.id}')">${u.role==="manager"?"Review":"Open"}</button></article>`).join("")}`);}
function viewQueue(){const f=state.filter;const list=state.rooms.filter(r=>f==="all"?true:f==="queue"?(r.status==="submitted"||r.status==="returned"):r.status===f);return shell(`<p class="kicker">Duty office \u00b7 live queue</p><div class="page-h"><h1>Certify</h1></div><div class="thumbs" style="margin-bottom:12px">${["queue","pending","submitted","certified","returned","all"].map(x=>`<button class="btn ${state.filter===x?"gold":"line"}" style="padding:7px 12px" onclick="state.filter='${x}';render()">${x}</button>`).join("")}</div>${list.map(r=>{const hk=USERS.find(u=>u.id===r.hk);return `<article class="room"><div class="rno">${r.number}</div><div><div>${r.type}</div><div class="meta">${r.site} \u00b7 ${hk.name.split(" ")[0]} \u00b7 ${label(r.status)}</div></div><button class="btn gold" onclick="openRoom('${r.id}')">Open</button></article>`;}).join("")||`<p class="kicker">Nothing in this filter.</p>`}`);}
function viewRoom(){const r=room(state.roomId);const locked=r.status==="certified"||r.status==="submitted";return shell(`<p class="kicker"><a href="#" onclick="state.tab='rooms';render();return false">\u2190 Rooms</a> \u00b7 ${r.site}</p><div class="page-h"><h1>Room ${r.number}</h1><span class="pill ${r.status==="certified"?"ok":r.status==="returned"?"bad":"warn"}">${label(r.status)}</span></div>${r.status==="returned"&&r.managerNotes?`<div class="banner" style="background:#8c3a32"><h3>Returned</h3><p>${esc(r.managerNotes)}</p></div>`:""}<div class="split"><article><h3>Normal hotel</h3><ul>${STANDARD.map(x=>`<li>${x}</li>`).join("")}</ul></article><article class="hi"><h3>Posh Nigeria</h3><ul><li>Every departure room</li><li>12 photo points</li><li>Duty manager before Front Office sells</li></ul></article></div>${POSH.map(p=>{const ev=r.evidence[p.id];return `<section class="item"><header style="display:flex;justify-content:space-between"><h3>${p.title}</h3><span class="kicker">${ev.done?"Attached":p.need}</span></header><p class="vs">${p.vs}</p><div class="thumbs">${ev.files.map(f=>f.kind==="video"?`<video class="thumb" src="${f.src||""}" controls></video>`:`<img class="thumb" src="${f.src||ph()}" alt="">`).join("")}${locked?"":`<label class="btn line file">Photo<input type="file" accept="image/*" capture="environment" onchange="addFile('${r.id}','${p.id}',this)"></label>${p.id==="tech"?`<label class="btn line file">Video<input type="file" accept="video/*" capture="environment" onchange="addFile('${r.id}','${p.id}',this)"></label>`:""}`}</div></section>`;}).join("")}<label class="kicker">Note to duty manager</label><textarea id="hkNotes" ${locked?"disabled":""}>${esc(r.notes)}</textarea><div class="row"><button class="btn line" onclick="saveRoom('${r.id}',false)">Save</button><button class="btn gold" onclick="saveRoom('${r.id}',true)" ${r.status==="certified"?"disabled":""}>Send to manager</button></div>`);}
function viewReview(){const r=room(state.roomId);const hk=USERS.find(u=>u.id===r.hk);return shell(`<p class="kicker"><a href="#" onclick="state.tab='queue';render();return false">\u2190 Queue</a></p><div class="page-h"><h1>Certify ${r.number}</h1><span class="pill warn">${r.site}</span></div><p class="meta">${r.type} \u00b7 ${hk.name}</p><div class="thumbs" style="margin:12px 0">${POSH.map(p=>{const ev=r.evidence[p.id];const f=ev.files[0];return `<img class="thumb" src="${(f&&f.src)||ph()}" alt="${p.title}">`;}).join("")}</div><label class="kicker">Manager notes</label><textarea id="mgrNotes">${esc(r.managerNotes)}</textarea><div class="row"><button class="btn ok" onclick="decide('${r.id}','certified')">Certify room</button><button class="btn bad" onclick="decide('${r.id}','returned')">Return to floor</button></div>`);}
function viewStandards(){return shell(`<p class="kicker">Quality standard</p><div class="page-h"><h1>Posh vs normal</h1></div><div class="split"><article><h3>Normal hotel</h3><ul>${STANDARD.map(x=>`<li>${x}</li>`).join("")}</ul></article><article class="hi"><h3>Posh Nigeria</h3><ul>${POSH.map(p=>`<li>${p.title}</li>`).join("")}</ul></article></div>`);}
function viewMe(){const u=state.user;const s=stats(u.role==="manager"?null:u.id);return shell(`<p class="kicker">${today()}</p><div class="page-h"><h1>Account</h1></div><article class="item"><h3>${esc(u.name)}</h3><p class="vs">${esc(u.title)} \u00b7 ${esc(u.site)}</p><p class="meta">${s.certified}/${s.total} certified today</p></article><article class="item"><h3>Hosted</h3><p class="vs">This is the live Posh Certify page. Work saves in this phone browser.</p></article>${u.role==="manager"?`<article class="item"><h3>Add a live room</h3><input id="newNo" placeholder="Room number" style="width:100%;padding:10px;border-radius:12px;border:1px solid var(--line);margin:6px 0"><input id="newSite" value="Ikeja" style="width:100%;padding:10px;border-radius:12px;border:1px solid var(--line);margin:6px 0"><input id="newType" placeholder="Deluxe King" style="width:100%;padding:10px;border-radius:12px;border:1px solid var(--line);margin:6px 0"><button class="btn gold wide" onclick="addLiveRoom()">Save room to board</button></article>`:""}<button class="btn line wide" onclick="logout()">Sign out</button>`);}
function addLiveRoom(){const number=(document.getElementById("newNo")||{}).value.trim();const site=(document.getElementById("newSite")||{}).value.trim()||"Ikeja";const type=(document.getElementById("newType")||{}).value.trim()||"Deluxe";if(!number){toast("Enter a room number.");return;}state.rooms.push({id:"x"+Date.now(),number,site,type,hk:"blessing",status:"pending",notes:"",managerNotes:"",evidence:emptyEv()});persist();toast("Room "+number+" is on the board.");state.tab="rooms";render();}
function addFile(id,pid,input){const file=input.files&&input.files[0];if(!file)return;const packed={name:file.name,kind:file.type.startsWith("video")?"video":"photo",src:URL.createObjectURL(file)};const rm=room(id);rm.evidence[pid].files.push(packed);rm.evidence[pid].done=true;persist();toast(packed.kind==="video"?"Walkthrough attached.":"Photo attached.");render();}
function saveRoom(id,submit){const r=room(id);const ta=document.getElementById("hkNotes");if(ta)r.notes=ta.value;if(submit){if(!ready(r)){toast("Attach every Posh point first.");persist();return;}r.status="submitted";persist();toast("Room "+r.number+" sent to duty manager.");const msg=encodeURIComponent("POSH CERTIFY \u00b7 "+r.site+"\nRoom "+r.number+" is in your queue.");window.open("https://wa.me/2348012345678?text="+msg,"_blank");state.tab="rooms";render();return;}persist();toast("Saved on this phone.");}
function decide(id,status){const r=room(id);const notes=(document.getElementById("mgrNotes")||{}).value||"";if(status==="returned"&&!notes.trim()){toast("Say what failed the Posh standard.");return;}r.status=status;r.managerNotes=notes;persist();const st=stats(r.hk);const hk=USERS.find(u=>u.id===r.hk);toast(status==="certified"?(st.cleared?"Certified. "+hk.name.split(" ")[0]+" is cleared for the day.":"Room "+r.number+" certified."):"Returned to the floor.");state.tab="queue";render();}
function render(){const root=document.getElementById("app");if(state.view==="login"||!state.user){root.className="auth";root.innerHTML=viewLogin();return;}root.className="";const map={rooms:viewRooms,queue:viewQueue,room:viewRoom,review:viewReview,standards:viewStandards,me:viewMe};root.innerHTML=(map[state.tab]||viewRooms)();}
load();render();
